### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by wasabii** [pomma89/ObjectPool#11]
I have some objects I'd like to pool, but their initialization is Async. They represent connections to remote resources.

What do you think about Async version of the pools?

**Comment by pomma89** [comment]
Hello @wasabii,

Having async pools seems a good idea. However:

- I will need to check which impacts this feature would have (I suspect many).
- If it is feasible, I will need a few days in order to implement it (I work on this project during my spare time).

So, I'll let you know soon whether this is feasile or not.

Thanks,
Alessio

**Comment by pomma89** [comment]
Hello @wasabii,

I confirm that I'm working on this feature. It will be ready during next week.

Bye,
Alessio

**Comment by pomma89** [comment]
Done and released on NuGet.

Here is a little summary of the feature:

https://github.com/pomma89/ObjectPool#async-support

You should be able to specify an async factory during pool construction.

Let me know if you have any issues.
