### ISSUE TITLE
Pool initialization from a fixed list of items

### ISSUE THREAD

**Issue by znyet** [pomma89/ObjectPool#14]
```c#

//an class like
 public class Demo : PooledObject
    {
        string _name;
        public Demo(string name)
        {
            _name = name;
        }

        public string GetName()
        {
            return _name;
        }
    }

//and  your dll can only Initialization with
var pool= new ObjectPool<Demo>(10, () => new Demo("lili"));

using (var demo = pool.GetObject())
 {
       Console.WriteLine(demo.GetName());  // all the object name is lili
}

//can you install with List<Demo> ? Like

List<Demo> list = new List<Demo>();
var demo1 = new Demo("lili");
var demo2 = new Demo("jone");
list.Add(demo1);
list.Add(demo2);
var pool= new ObjectPool<Demo>(list);
using (var demo = pool.GetObject())
 {
       Console.WriteLine(demo.GetName());  // when i get object i can different name
}
```

**Comment by pomma89** [comment]
Hello @znyet,

What you ask, initialization from a list, is not implemented for a reason: if you provide a list with N items, and you find yourself in a situation with N+1 consumers which exaust the pool, how should the pool behave?

It should not block, because this is not in the philosophy of this library, but it cannot create new items either, because it was initialized from a list.

A more accettable solution would be providing an initialization function and a list; in fact, this solution would overcome the limitation described above, but the function should be able to provide items which are not in the list.

I hope I have explained the issue I see.

Thanks,
Alessio

**Comment by znyet** [comment]
You are right, thank you!
My starting point is to use your class library to achieve load balancing,
and all the object must be not dispose. 
when initialize 10 object in pool,the pool must be10 object.
create by myself.

**Comment by pomma89** [comment]
Hello @znyet,

Thanks for the explanation. If I understood your use case correctly, then this library is not OK for you, but I think that you can simply use `ConcurrentQueue<T>` from the BCL ([official documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1?view=netframework-4.8)).

You could initialize the queue with 10 objects and each balanced process could simply dequeue an object, returning it using enqueue after usage. The queue also allows concurrent usage, as the name suggests.

Bye,
Alessio

**Comment by znyet** [comment]
Thank you very much！
