### ISSUE TITLE
fit Microsoft.Extensions.ObjectPool 

### ISSUE THREAD

**Issue by uliian** [pomma89/ObjectPool#7]
I think we can make a Microsoft.Extensions.ObjectPool fit, what do you think? Some projects use Microsoft.Extensions.ObjectPool, we can quickly replace

**Comment by pomma89** [comment]
Hi @uliian,

Sorry for late answer. What do you mean with "make a Microsoft.Extensions.ObjectPool fit"?

If you mean implementing/adapting following base class:

https://github.com/aspnet/Common/blob/dev/src/Microsoft.Extensions.ObjectPool/ObjectPool.cs

Then it might be OK, but we should build a different package, since implementing that class implies taking a dependency on Microsoft.Extensions.ObjectPool package and I would like not to do that on existing package. The result would be something like "CodeProject.ObjectPool.Microsoft" package, which would contain an adapter class which extends Microsoft ObjectPool base class and adapts our existing pools to that one.

If you mean something different, could you clarify? Thanks!

**Comment by uliian** [comment]
Yes, that's what it means. We have a team that uses Microsoft.Extensions.Objectpool, but wants to replace, if the direct replacement objectpool cost is a bit high, so hopefully there's a way to lower the cost of migrating over

**Comment by pomma89** [comment]
Sorry it took so long, but I was too busy at work... However, it is done and published on NuGet:

https://www.nuget.org/packages/CodeProject.ObjectPool.MicrosoftExtensionsAdapter/

Please have a look at the examples and the tests in order to understand how to use it. Let me know if this was not what you or your team neeeded.

**Comment by uliian** [comment]
great!!!! it's very good!!!!
thank you very much!!!!!!

**Comment by pomma89** [comment]
You're welcome! I'm closing this for now, feel free to reopen if there is something wrong.
